apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- deployment.yaml
- serviceaccount.yaml
- service.yaml
- virtualservice.yaml
- destination-rule.yaml
- authorization-policy.yaml
