apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base-1-17
- kserve-gateway.yaml
- issuer.yaml
patches:

- path: patches/gateway-selector-in-istio-system.yaml
- path: patches/gateway-selector-in-knative-serving.yaml
- target:
    version: v1
    kind: ConfigMap
    name: config-domain
  patch: |-
    - op: add
      path: /data/kserve.86labs.cloud
      value: ""
- path: patches/istio.config.map.yaml
  target:
    version: v1
    kind: ConfigMap
    name: config-istio
# - patch: |-
#     - op: remove
#       path: /data/gateway.kubeflow.kubeflow-gateway
#   target:
#     version: v1
#     kind: ConfigMap
#     name: config-istio
- path: patches/network.config.map.yaml
  target:
      version: v1
      kind: ConfigMap
      name: config-network
- patch: |-
    - op: remove
      path: /data/_example
  target:
    version: v1
    kind: ConfigMap
    name: config-network
- patch: |-
    - op: remove
      path: /data/_example
  target:
    version: v1
    kind: ConfigMap
    name: config-istio
- target:
    version: v1
    kind: ConfigMap
    name: config-certmanager
  patch: |-
    - op: replace
      path: /data/issuerRef
      value: |
        kind: ClusterIssuer
        name: letsencrypt-prod
