apiVersion: v1
kind: ConfigMap
metadata:
  name: kfp-launcher
data:
  defaultPipelineRoot: $(kfp-default-pipeline-root)
  providers: |-
    s3:
      default:
        endpoint: s3.86labs.cloud
        disableSSL: false
        region: us-east-1
        credentials:
          fromEnv: false
          secretRef:
            secretName: mlpipeline-minio-artifact
            accessKeyKey: accesskey
            secretKeyKey: secretkey
