apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-oidc-secret
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store               # name of the SecretStore (or kind specified)
  target:
    name: oauth2-proxy-oidc-secret    # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: "Opaque"
      data:
        client-id: "{{ .OIDC_CLIENT_ID }}"
        client-secret: "{{ .OIDC_CLIENT_SECRET }}"
        cookie-secret: "{{ .OIDC_COOKIE_SECRET }}"
  dataFrom:
  - extract:
      key: infra/kubeflow/prereqs/oidc
