apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- external-secret.yaml
components:
- ../../components/istio-external-auth
- ../../components/istio-m2m

configMapGenerator:
- name: oauth2-proxy
  files:
  - oauth2_proxy.cfg
  behavior: replace
- name: oauth2-proxy-parameters
  behavior: merge
  literals:
  # Configs for oauth2-proxy
  - FORCE_HTTPS=true # sets `secure` flag on cookies, requires HTTPS on the gateway
  - ALLOW_SELF_SIGNED_ISSUER=true
patches:
  - path: patches/deployment.yaml
  - path: patches/requestauthentication.dex-jwt.yaml
  - patch: |-
      - op: replace
        path: /spec/jwtRules/0/issuer
        value: https://s3.us-east-1.amazonaws.com/oidc-irsa-86labs-com/metal
      - op: replace
        path: /spec/jwtRules/0/jwksUri
        value: https://s3.us-east-1.amazonaws.com/oidc-irsa-86labs-com/metal/keys.json
    target:
      group: security.istio.io
      version: v1beta1
      kind: RequestAuthentication
      name: m2m-token-issuer
      namespace: istio-system
