apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kubeflow.86labs.cloud,*.kubeflow.86labs.cloud
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
