apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-oidc-client
  namespace: auth
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store               # name of the SecretStore (or kind specified)
  target:
    name: dex-oidc  # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: "Opaque"
      data:
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
  - extract:
      key: infra/kubeflow/prereqs/oidc
