apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - NetworkPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
- ../../common/cert-manager/kubeflow-issuer/base
# Istio
- ../../common/istio-1-24/istio-crds/base
- ../../common/istio-1-24/istio-namespace/base
- ../../common/istio-1-24/istio-install/overlays/86labs
- ../../common/oauth2-proxy/overlays/86labs    # for all clusters
- ../../common/dex/overlays/86labs
# Kubeflow namespace
- ../../common/kubeflow-namespace/base
# NetworkPolicies
- ../../common/networkpolicies/base
# Kubeflow Roles
- ../../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../../common/istio-1-24/kubeflow-istio-resources/overlays/86labs
# Central Dashboard
- ../../apps/centraldashboard/overlays/oauth2-proxy
# Admission Webhook
- ../../apps/admission-webhook/upstream/overlays/cert-manager
# Jupyter Web App
- ../../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Notebook Controller
- ../../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../../apps/profiles/upstream/overlays/kubeflow
# PVC Viewer
- ../../apps/pvcviewer-controller/upstream/base
# Volumes Web App
- ../../apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
- ../../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
- ../../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Kubeflow Pipelines
- ../../apps/pipeline/upstream/env/86labs
# katib
- ../apps/katib/upstream/installs/katib-with-kubeflow
