apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store               # name of the SecretStore (or kind specified)
  target:
    name: mysql-secret    # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: "Opaque"
      data:
        username: "{{ .rootUser }}"
        password: "{{ .rootPassword }}"
  dataFrom:
  - extract:
      key: infra/kubeflow/prereqs/mysql     # name of the GCPSM secret key
