apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlpipeline-minio-artifact
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store               # name of the SecretStore (or kind specified)
  target:
    name: mlpipeline-minio-artifact   # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: "Opaque"
      data:
        OBJECTSTORECONFIG_HOST: "s3.86labs.cloud"
        OBJECTSTORECONFIG_PORT: "443"
        OBJECTSTORECONFIG_REGION: "us-east-1"
        OBJECTSTORECONFIG_SECURE: "true"
        OBJECTSTORECONFIG_ACCESSKEY: "{{ .accessKey }}"
        OBJECTSTORECONFIG_SECRETACCESSKEY: "{{ .secretAccessKey }}"
        accesskey: "{{ .accessKey }}"
        secretkey: "{{ .secretAccessKey }}"
  dataFrom:
  - extract:
      key: infra/kubeflow/objectstorage/ceph     # name of the GCPSM secret key
