apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow


resources:
  - ../../third-party/metacontroller/base
  - ../../base/installs/multi-user
  - ../../base/metadata/base
  - ../../base/metadata/options/istio
  - ../../third-party/argo/installs/cluster
  - external-secret-object-storage.yaml
  - external-mysql-secret.yaml
  - ../cert-manager/base

configMapGenerator:
  - name: pipeline-install-config
    env: params.env
    behavior: merge
  - name: workflow-controller-configmap
    behavior: replace
    files:
      - config
  - name: ml-pipeline-ui-configmap
    behavior: replace
    files:
      - viewer-pod-template.json
  - name: kubeflow-pipelines-profile-controller-code
    behavior: replace
    files:
    - sync.py
generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patches/aws-configuration-pipeline-patch.yaml
  - path: patches/aws-configuration-pipeline-ui-patch.yaml
  - path: patches/delete.mysql.secret.yaml
  - path: patches/kfp-launcher-configmap-patch.yaml

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--tls_cert_filename=tls.crt"
    target:
      kind: Deployment
      name: cache-server
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--tls_key_filename=tls.key"
    target:
      kind: Deployment
      name: cache-server


# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines
