apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - gateway_authorizationpolicy.yaml
  - deny_all_authorizationpolicy.yaml
  - install.yaml



patches:
- path: patches/disable-debugging.yaml
- path: patches/istio-ingressgateway-remove-pdb.yaml
- path: patches/istiod-remove-pdb.yaml
- path: patches/seccomp-istio-ingressgateway.yaml
- path: patches/seccomp-istiod.yaml

images:
- name: busybox
  newName: registry.k8s.io/busybox
