apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-s3-secret
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store               # name of the SecretStore (or kind specified)
  target:
    name: mlflow-s3-secret   # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: "Opaque"
      data:
        endpoint-url: "{{ .endpointurl }}"
        bucket: "{{ .bucket }}"
        accesskey: "{{ .accesskey }}"
        secretkey: "{{ .secretkey }}"
  dataFrom:
  - extract:
      key: infra/kubeflow/mlflow/objectstore    # name of the GCPSM secret key
