apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-db-secret
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store               # name of the SecretStore (or kind specified)
  target:
    name: mlflow-db-secret   # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      type: "Opaque"
      data:
        username: "{{ .username }}"
        host: "{{ .host }}"
        password: "{{ .password }}"
        dbname: "{{ .dbname }}"
  dataFrom:
  - extract:
      key: infra/kubeflow/mlflow/database   # name of the GCPSM secret key
