---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-sqllite
  namespace: kubeflow
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
