apiVersion: v1
kind: ConfigMap

metadata:
  name: config-istio
  namespace: knative-serving
data:
  # TODO(nghia): Extract the .svc.cluster.local suffix into its own config.
  external-gateways: |
    - name: kserve-gateway
      namespace: knative-serving
      service: kserve-ingress.istio-system.svc.cluster.local
  local-gateways: |
    - name: knative-local-gateway
      namespace: knative-serving
      service: knative-local-gateway.istio-system.svc.cluster.local
