apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
spec:
  template:
    spec:
      containers:
      - name: dex
        envFrom:
        - secretRef:
            name: dex-oidc
        - secretRef:
            name: dex-passwords
